// ------------------------------------------------------------------
// 🏗️ SCAFFOLDING GENERATED BY TESTSPRITE
// Modules: SignInPage, SignUpPage
// ------------------------------------------------------------------
import { jest } from '@jest/globals';

// --- STUBS ---
export const mockUser = { id: 'u1', email: 'test@example.com', role: 'customer' };

// --- MOCKS ---
export const mockRouter = { push: jest.fn() };
export const mockAuthActions = {
  signIn: jest.fn(),
  signUp: jest.fn(),
  user: null,
};

// --- DRIVER ---
export const setupAuthScaffolding = (scenario: 'success' | 'error' = 'success') => {
  jest.clearAllMocks();

  // 1. Mock Router
  jest.mock('next/navigation', () => ({
    useRouter: () => mockRouter,
  }));

  // 2. Mock Auth Context
  jest.mock('@/lib/auth-context', () => ({
    useAuth: () => mockAuthActions,
  }));

  // 3. Scenario Configuration
  if (scenario === 'success') {
    mockAuthActions.signIn.mockResolvedValue(true);
    mockAuthActions.signUp.mockResolvedValue(true);
  } else {
    mockAuthActions.signIn.mockRejectedValue(new Error('Invalid credentials'));
    mockAuthActions.signUp.mockRejectedValue(new Error('Email already in use'));
  }
};