// ------------------------------------------------------------------
// 🏗️ SCAFFOLDING GENERATED BY TESTSPRITE
// Module Under Test (MUT): AdminPage
// ------------------------------------------------------------------

import { jest } from '@jest/globals';

// --- 1. STUBS (Data Replacements) ---
// These replace the actual data usually fetched from the database.

export const mockVendorsData = [
  { id: 'v1', business_name: 'TechStore', payout_email: 'tech@test.com', status: 'active', total_sales: 1500, rating: 4.5 },
  { id: 'v2', business_name: 'FashionHub', payout_email: 'style@test.com', status: 'pending', total_sales: 0, rating: 0 },
];

export const mockStatsData = {
  products: [{ id: 'p1' }, { id: 'p2' }, { id: 'p3' }], // 3 products
  orders: [{ total_amount: 100 }, { total_amount: 200 }], // Total revenue 300
  subOrders: [{ commission: 10 }, { commission: 20 }] // Platform commission 30
};

export const mockAdminProfile = { role: 'admin', id: 'admin-123' };
export const mockUserProfile = { role: 'user', id: 'user-456' };


// --- 2. MOCKS (Dependency Replacements) ---
// These replace external libraries (Supabase, Auth, Router)

// A. Mocking the Navigation (Driver for URL changes)
const mockPush = jest.fn();
export const mockRouter = {
  push: mockPush,
  // Reset function to clear history between tests
  __reset: () => mockPush.mockClear(),
};

// B. Mocking the Auth Context
export const mockUseAuth = jest.fn(); 

// C. Mocking Supabase (The most complex dependency)
// We create a "Chainable Mock" to handle: supabase.from().select().order()
export const mockSupabaseClient = {
  from: jest.fn().mockReturnThis(),
  select: jest.fn().mockReturnThis(),
  order: jest.fn().mockReturnThis(),
  update: jest.fn().mockReturnThis(),
  eq: jest.fn().mockReturnThis(),
  // Default resolved values (Stubs)
  then: jest.fn((resolve) => resolve({ data: [], error: null })), 
};


// --- 3. DRIVER (Test Harness) ---
// This function sets up the environment before the MUT is mounted.

export const setupScaffolding = (scenario = 'success') => {
  // Reset all mocks
  jest.clearAllMocks();
  mockRouter.__reset();

  // inject the Router Mock
  jest.mock('next/navigation', () => ({
    useRouter: () => mockRouter,
  }));

  // inject the Auth Mock
  jest.mock('@/lib/auth-context', () => ({
    useAuth: mockUseAuth,
  }));

  // inject the Supabase Mock
  jest.mock('@/lib/supabase', () => ({
    supabase: mockSupabaseClient,
  }));

  // Configure Scenario-Specific Behavior
  if (scenario === 'success') {
    mockUseAuth.mockReturnValue({ user: { email: 'admin@test.com' }, profile: mockAdminProfile });
    
    // Configure Supabase to return our Stub data
    mockSupabaseClient.from.mockImplementation((table) => {
      const chain = {
        select: jest.fn().mockReturnThis(),
        order: jest.fn().mockReturnThis(),
        update: jest.fn().mockReturnThis(),
        eq: jest.fn().mockReturnThis(),
        then: jest.fn((resolve) => {
          // Return specific stub data based on the table requested
          if (table === 'vendors') resolve({ data: mockVendorsData, error: null });
          if (table === 'products') resolve({ data: mockStatsData.products, error: null });
          if (table === 'orders') resolve({ data: mockStatsData.orders, error: null });
          if (table === 'sub_orders') resolve({ data: mockStatsData.subOrders, error: null });
          return resolve({ data: [], error: null });
        })
      };
      return chain;
    });
  } 
  
  else if (scenario === 'unauthorized') {
    mockUseAuth.mockReturnValue({ user: { email: 'user@test.com' }, profile: mockUserProfile });
  }
};