// ------------------------------------------------------------------
// 🏗️ SCAFFOLDING GENERATED BY TESTSPRITE
// Modules: CartPage, CheckoutPage
// ------------------------------------------------------------------
import { jest } from '@jest/globals';

// --- STUBS ---
export const mockCartItems = [
  { 
    id: 'c1', 
    quantity: 2, 
    product_id: 'p1', 
    product: { 
      id: 'p1', price: 50, name: 'Gadget', stock: 100, vendor_id: 'v1', 
      vendor: { commission_rate: 10, user_id: 'vendor_user_1' } 
    } 
  }
];

export const mockOrderResponse = { id: 'order_123', total_amount: 100 };
export const mockSubOrderResponse = { id: 'sub_456' };

// --- MOCKS ---
const mockRouter = { push: jest.fn() };
const mockUser = { id: 'customer_1', email: 'me@test.com' };

// Complex Supabase Mock for Transactional Writes
const mockSupabase = {
  from: jest.fn().mockReturnThis(),
  select: jest.fn().mockReturnThis(),
  insert: jest.fn().mockReturnThis(),
  update: jest.fn().mockReturnThis(),
  delete: jest.fn().mockReturnThis(),
  eq: jest.fn().mockReturnThis(),
  single: jest.fn().mockReturnThis(), // Needed for .select().single()
  // Default Resolver
  then: jest.fn((resolve) => resolve({ data: [], error: null })),
};

// --- DRIVER ---
export const setupCheckoutScaffolding = () => {
  jest.clearAllMocks();

  // Inject Dependencies
  jest.mock('next/navigation', () => ({ useRouter: () => mockRouter }));
  jest.mock('@/lib/auth-context', () => ({ useAuth: () => ({ user: mockUser }) }));
  jest.mock('@/lib/supabase', () => ({ supabase: mockSupabase }));

  // Configure Responses for the Checkout Flow
  mockSupabase.from.mockImplementation((table) => {
    const chain = {
      select: jest.fn().mockReturnThis(),
      insert: jest.fn().mockReturnThis(),
      update: jest.fn().mockReturnThis(),
      delete: jest.fn().mockReturnThis(),
      eq: jest.fn().mockReturnThis(),
      single: jest.fn().mockReturnThis(),
      then: jest.fn((resolve) => {
        // Return different data based on which table is queried
        if (table === 'cart_items') resolve({ data: mockCartItems, error: null });
        if (table === 'orders') resolve({ data: mockOrderResponse, error: null });
        if (table === 'sub_orders') resolve({ data: mockSubOrderResponse, error: null });
        resolve({ data: [], error: null });
      })
    };
    return chain;
  });
};