// ------------------------------------------------------------------
// 🏗️ SCAFFOLDING GENERATED BY TESTSPRITE
// Module: MarketplacePage
// ------------------------------------------------------------------
import { jest } from '@jest/globals';

// --- STUBS (Product Data) ---
export const mockProducts = [
  { id: 'p1', name: 'Wireless Mouse', category: 'Electronics', price: 29.99, status: 'active', vendor: { business_name: 'TechStore' } },
  { id: 'p2', name: 'Running Shoes', category: 'Sports', price: 89.99, status: 'active', vendor: { business_name: 'Sporty' } },
  { id: 'p3', name: 'Coffee Maker', category: 'Home', price: 49.99, status: 'active', vendor: { business_name: 'HomeGood' } },
];

// --- MOCKS ---
// Recursive mock to handle: supabase.from().select().eq().order().ilike()
const mockSupabaseChain = {
  select: jest.fn().mockReturnThis(),
  eq: jest.fn().mockReturnThis(),
  order: jest.fn().mockReturnThis(),
  ilike: jest.fn().mockReturnThis(),
  then: jest.fn((resolve) => resolve({ data: mockProducts, error: null })),
};

export const mockSupabase = {
  from: jest.fn(() => mockSupabaseChain),
};

// --- DRIVER ---
export const setupMarketplaceScaffolding = () => {
  jest.clearAllMocks();

  jest.mock('@/lib/supabase', () => ({
    supabase: mockSupabase,
  }));

  // Driver utility to inspect what the component tried to fetch
  return {
    verifySearch: (term: string) => {
      expect(mockSupabaseChain.ilike).toHaveBeenCalledWith('name', `%${term}%`);
    },
    verifyCategoryFilter: (category: string) => {
      expect(mockSupabaseChain.eq).toHaveBeenCalledWith('category', category);
    }
  };
};